SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE , PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM 
    (select SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    from OFFLINE_SALE 

    union all

    select SALES_DATE,  PRODUCT_ID, USER_ID, SALES_AMOUNT
    from ONLINE_SALE) A
WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
ORDER BY 1,2,3