-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * ((100-DISCOUNT_RATE) / 100),0) FEE

FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE IN ('세단', 'SUV')) C 
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
    ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'

WHERE CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE ("2022-11-01" BETWEEN START_DATE AND END_DATE)
    OR ("2022-11-31" BETWEEN START_DATE AND END_DATE)) 

GROUP BY CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000

ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;