-- 코드를 입력하세요
SELECT b.HOUR, COUNT(a.HOUR) COUNT
FROM (SELECT TO_CHAR(DATETIME, 'HH24') HOUR FROM ANIMAL_OUTS) a,
      (SELECT level-1 HOUR FROM DUAL CONNECT BY LEVEL <= 24) b
WHERE a.HOUR(+) = b.HOUR
GROUP BY b.HOUR
ORDER BY b.HOUR;
