SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES * B.PRICE) as TOTAL_SALES FROM BOOK_SALES A, BOOK B, AUTHOR C
WHERE A.BOOK_ID=B.BOOK_ID 
AND  B.AUTHOR_ID=C.AUTHOR_ID 
AND EXTRACT(YEAR FROM SALES_DATE) = 2022 
AND EXTRACT(MONTH FROM SALES_DATE) = 1
GROUP BY C.AUTHOR_ID,C.AUTHOR_NAME,B.CATEGORY ORDER BY C.AUTHOR_ID ASC, B.CATEGORY DESC
