-- 코드를 입력하세요
WITH REVIEW_COUNT AS (
    SELECT R.MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW R
    GROUP BY R.MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
),

SELECT_REVIEW AS (
    SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
    WHERE R.MEMBER_ID = (SELECT MEMBER_ID FROM REVIEW_COUNT)
)
SELECT *
FROM SELECT_REVIEW
ORDER BY REVIEW_DATE, REVIEW_TEXT;