-- 코드를 작성해주세요
SELECT DISTINCT E.ITEM_ID, E.ITEM_NAME, E.RARITY
FROM ITEM_INFO I, ITEM_TREE T, ITEM_INFO E
WHERE I.ITEM_ID = T.PARENT_ITEM_ID AND I.RARITY = 'RARE' AND T.ITEM_ID = E.ITEM_ID 
ORDER BY E.ITEM_ID DESC;