-- 코드를 작성해주세요
WITH MAX_SIZE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE))
    
SELECT MAX_SIZE.YEAR, (MAX_SIZE.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY) YEAR_DEV, ECOLI_DATA.ID
FROM MAX_SIZE JOIN ECOLI_DATA
ON MAX_SIZE.YEAR = YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;